# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [434]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [6]:
import pandas as pd 
import datetime as dt

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

In [17]:
url='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'
data=pd.read_table(url, sep='\s+' , skiprows=1)
data.head(1)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\USER\AppData\Local\Temp\ipykernel_1400\1112957966.py:2: SyntaxWarning: invalid escape sequence '\s'
  data=pd.read_table(url, sep='\s+' , skiprows=1)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.5,15.04

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [18]:
data=pd.read_table(url, sep='\s+' , skiprows=1,parse_dates=[[0,1,2]])
data.head(20)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\USER\AppData\Local\Temp\ipykernel_1400\997553295.py:1: SyntaxWarning: invalid escape sequence '\s'
  data=pd.read_table(url, sep='\s+' , skiprows=1,parse_dates=[[0,1,2]])
C:\Users\USER\AppData\Local\Temp\ipykernel_1400\997553295.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_table is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data=pd.read_table(url, sep='\s+' , skiprows=1,parse_dates=[[0,1,2]])
C:\Users\USER\AppData\Local\Temp\ipykernel_1400\997553295.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data=pd.read_table(url, sep='\s+' , skiprows=1,parse_dates=[[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
5,2061-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17
6,2061-01-07,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79
7,2061-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46
8,2061-01-09,12.58,10.83,10.00,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37
9,2061-01-10,13.37,11.12,19.50,8.33,9.71,6.54,11.42,7.79,8.54,9.00,8.58,11.83
10,2061-01-11,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92
11,2061-01-12,19.75,12.08,18.50,10.54,10.29,9.46,15.54,11.50,10.37,14.58,15.59,14.09
12,2061-01-13,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04
13,2061-01-14,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.50,2.67,7.17,5.17
14,2061-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75
15,2061-01-16,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04
16,2061-01-17,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08
17,2061-01-18,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96
18,2061-01-19,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83
19,2061-01-20,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [28]:
def fix_year(x):
    year = x.year-100 if x.year>1989 else x.year
    return dt.date(year , x.month , x.day)

data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_year)



data.head(20)

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
5,1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17
6,1961-01-07,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79
7,1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46
8,1961-01-09,12.58,10.83,10.00,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37
9,1961-01-10,13.37,11.12,19.50,8.33,9.71,6.54,11.42,7.79,8.54,9.00,8.58,11.83
10,1961-01-11,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92
11,1961-01-12,19.75,12.08,18.50,10.54,10.29,9.46,15.54,11.50,10.37,14.58,15.59,14.09
12,1961-01-13,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04
13,1961-01-14,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.50,2.67,7.17,5.17
14,1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75
15,1961-01-16,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04
16,1961-01-17,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08
17,1961-01-18,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96
18,1961-01-19,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83
19,1961-01-20,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [29]:
data['Yr_Mo_Dy'].dtype
data['Yr_Mo_Dy']=pd.to_datetime(data['Yr_Mo_Dy'])

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [30]:
data.head(2)
data.isnull().sum()

Yr_Mo_Dy    0
RPT         6
VAL         3
ROS         2
KIL         5
SHA         2
BIR         0
DUB         3
CLA         2
MUL         3
CLO         1
BEL         0
MAL         4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [23]:
data.notnull().sum().sum()

85431

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [34]:
data.describe()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6574,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,1969-12-31 12:00:00,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
min,1961-01-01 00:00:00,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,1965-07-02 06:00:00,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,1969-12-31 12:00:00,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,1974-07-01 18:00:00,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,1978-12-31 00:00:00,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
std,NaN,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [37]:
data.agg(['min','max','mean','std'], axis=1)

TypeError: '<=' not supported between instances of 'Timestamp' and 'float'

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

### Step 12. Downsample the record to a yearly frequency for each location.

### Step 13. Downsample the record to a monthly frequency for each location.

### Step 14. Downsample the record to a weekly frequency for each location.

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.